import { createTheme } from "./helpers.js";

const catppuccinLatteTheme = createTheme({
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    description: "Warm creamy light palette with soft pastels and gentle contrast.",
    page: {
        background: "#eff1f5",
        foreground: "#4c4f69",
        overlayBackground: "#eff1f5",
        overlayForeground: "#4c4f69",
        hintColor: "#8c8fa1",
        modalBackdrop: "rgba(239, 241, 245, 0.48)",
        modalBackground: "#e6e9ef",
        modalBorder: "#9ca0b0",
        modalForeground: "#4c4f69",
        modalMuted: "#8c8fa1",
        modalSelectedBackground: "#dce0e8",
        modalSelectedBorder: "#1e66f5",
        modalSelectedForeground: "#4c4f69",
    },
    terminal: {
        background: "#eff1f5",
        foreground: "#4c4f69",
        cursor: "#dc8a78",
        cursorAccent: "#eff1f5",
        selectionBackground: "rgba(30, 102, 245, 0.18)",
        black: "#5c5f77",
        red: "#d20f39",
        green: "#40a02b",
        yellow: "#df8e1d",
        blue: "#1e66f5",
        magenta: "#ea76cb",
        cyan: "#179299",
        white: "#acb0be",
        brightBlack: "#6c6f85",
        brightRed: "#d20f39",
        brightGreen: "#40a02b",
        brightYellow: "#df8e1d",
        brightBlue: "#1e66f5",
        brightMagenta: "#ea76cb",
        brightCyan: "#179299",
        brightWhite: "#bcc0cc",
    },
    tui: {
        surface: "#eff1f5",
        activeHighlightBackground: "#dce0e8",
        activeHighlightForeground: "#4c4f69",
        selectionBackground: "#1e66f5",
        selectionForeground: "#eff1f5",
        promptCursorBackground: "#dc8a78",
        promptCursorForeground: "#eff1f5",
    },
});

export default catppuccinLatteTheme;
