import { createTheme } from "./helpers.js";

const catppuccinMochaTheme = createTheme({
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    description: "Creamy dark palette with soft pastels and high legibility.",
    page: {
        background: "#1e1e2e",
        foreground: "#cdd6f4",
        overlayBackground: "#1e1e2e",
        overlayForeground: "#cdd6f4",
        hintColor: "#bac2de",
        modalBackdrop: "rgba(17, 17, 27, 0.74)",
        modalBackground: "#313244",
        modalBorder: "#585b70",
        modalForeground: "#cdd6f4",
        modalMuted: "#bac2de",
        modalSelectedBackground: "#45475a",
        modalSelectedBorder: "#89b4fa",
        modalSelectedForeground: "#cdd6f4",
    },
    terminal: {
        background: "#1e1e2e",
        foreground: "#cdd6f4",
        cursor: "#f5e0dc",
        cursorAccent: "#1e1e2e",
        selectionBackground: "rgba(137, 180, 250, 0.22)",
        black: "#45475a",
        red: "#f38ba8",
        green: "#a6e3a1",
        yellow: "#f9e2af",
        blue: "#89b4fa",
        magenta: "#f5c2e7",
        cyan: "#94e2d5",
        white: "#bac2de",
        brightBlack: "#585b70",
        brightRed: "#f38ba8",
        brightGreen: "#a6e3a1",
        brightYellow: "#f9e2af",
        brightBlue: "#89b4fa",
        brightMagenta: "#f5c2e7",
        brightCyan: "#94e2d5",
        brightWhite: "#f5e0dc",
    },
    tui: {
        surface: "#1e1e2e",
        activeHighlightBackground: "#45475a",
        activeHighlightForeground: "#cdd6f4",
        selectionBackground: "#89b4fa",
        selectionForeground: "#1e1e2e",
        promptCursorBackground: "#f5e0dc",
        promptCursorForeground: "#1e1e2e",
    },
});

export default catppuccinMochaTheme;
