import { createTheme } from "./helpers.js";

const cobalt2Theme = createTheme({
    id: "cobalt2",
    label: "Cobalt2",
    description: "Electric blue shell with bright yellow accents and saturated syntax colors.",
    page: {
        background: "#193549",
        foreground: "#ffffff",
        overlayBackground: "#193549",
        overlayForeground: "#ffffff",
        hintColor: "#a8c5e6",
        modalBackdrop: "rgba(7, 17, 28, 0.68)",
        modalBackground: "#224b68",
        modalBorder: "#2e6c99",
        modalForeground: "#ffffff",
        modalMuted: "#a8c5e6",
        modalSelectedBackground: "#ffc600",
        modalSelectedBorder: "#ffc600",
        modalSelectedForeground: "#193549",
    },
    terminal: {
        background: "#193549",
        foreground: "#ffffff",
        cursor: "#ffc600",
        cursorAccent: "#193549",
        selectionBackground: "rgba(255, 255, 255, 0.18)",
        black: "#000000",
        red: "#ff628c",
        green: "#3ad900",
        yellow: "#ff9d00",
        blue: "#0088ff",
        magenta: "#ff628c",
        cyan: "#80ffbb",
        white: "#ffffff",
        brightBlack: "#666666",
        brightRed: "#ff628c",
        brightGreen: "#3ad900",
        brightYellow: "#ff9d00",
        brightBlue: "#0088ff",
        brightMagenta: "#ff9d00",
        brightCyan: "#80ffbb",
        brightWhite: "#ffffff",
    },
    tui: {
        surface: "#193549",
        activeHighlightBackground: "#0f5f91",
        activeHighlightForeground: "#ffffff",
        selectionBackground: "#ffc600",
        selectionForeground: "#193549",
        promptCursorBackground: "#ffc600",
        promptCursorForeground: "#193549",
    },
});

export default cobalt2Theme;
