import { createTheme } from "./helpers.js";

const draculaTheme = createTheme({
    id: "dracula",
    label: "Dracula",
    description: "Classic Dracula contrast with neon green, pink, and violet accents.",
    page: {
        background: "#282a36",
        foreground: "#f8f8f2",
        overlayBackground: "#282a36",
        overlayForeground: "#f8f8f2",
        hintColor: "#bd93f9",
        modalBackdrop: "rgba(24, 25, 33, 0.72)",
        modalBackground: "#313442",
        modalBorder: "#6272a4",
        modalForeground: "#f8f8f2",
        modalMuted: "#bd93f9",
        modalSelectedBackground: "#44475a",
        modalSelectedBorder: "#bd93f9",
        modalSelectedForeground: "#f8f8f2",
    },
    terminal: {
        background: "#282a36",
        foreground: "#f8f8f2",
        cursor: "#f8f8f2",
        cursorAccent: "#282a36",
        selectionBackground: "rgba(189, 147, 249, 0.24)",
        black: "#21222c",
        red: "#ff5555",
        green: "#50fa7b",
        yellow: "#f1fa8c",
        blue: "#bd93f9",
        magenta: "#ff79c6",
        cyan: "#8be9fd",
        white: "#f8f8f2",
        brightBlack: "#6272a4",
        brightRed: "#ff6e6e",
        brightGreen: "#69ff94",
        brightYellow: "#ffffa5",
        brightBlue: "#d6acff",
        brightMagenta: "#ff92df",
        brightCyan: "#a4ffff",
        brightWhite: "#ffffff",
    },
    tui: {
        surface: "#282a36",
        activeHighlightBackground: "#44475a",
        activeHighlightForeground: "#f8f8f2",
        selectionBackground: "#bd93f9",
        selectionForeground: "#282a36",
        promptCursorBackground: "#f8f8f2",
        promptCursorForeground: "#282a36",
    },
});

export default draculaTheme;
