import { createTheme } from "./helpers.js";

const gruvboxDarkTheme = createTheme({
    id: "gruvbox-dark",
    label: "Gruvbox Dark",
    description: "Retro warm palette with earthy browns, oranges, and high readability.",
    page: {
        background: "#282828",
        foreground: "#ebdbb2",
        overlayBackground: "#282828",
        overlayForeground: "#ebdbb2",
        hintColor: "#a89984",
        modalBackdrop: "rgba(40, 40, 40, 0.74)",
        modalBackground: "#3c3836",
        modalBorder: "#504945",
        modalForeground: "#ebdbb2",
        modalMuted: "#a89984",
        modalSelectedBackground: "#504945",
        modalSelectedBorder: "#fabd2f",
        modalSelectedForeground: "#fbf1c7",
    },
    terminal: {
        background: "#282828",
        foreground: "#ebdbb2",
        cursor: "#ebdbb2",
        cursorAccent: "#282828",
        selectionBackground: "rgba(250, 189, 47, 0.22)",
        black: "#282828",
        red: "#cc241d",
        green: "#98971a",
        yellow: "#d79921",
        blue: "#458588",
        magenta: "#b16286",
        cyan: "#689d6a",
        white: "#a89984",
        brightBlack: "#928374",
        brightRed: "#fb4934",
        brightGreen: "#b8bb26",
        brightYellow: "#fabd2f",
        brightBlue: "#83a598",
        brightMagenta: "#d3869b",
        brightCyan: "#8ec07c",
        brightWhite: "#ebdbb2",
    },
    tui: {
        surface: "#282828",
        activeHighlightBackground: "#504945",
        activeHighlightForeground: "#fbf1c7",
        selectionBackground: "#fabd2f",
        selectionForeground: "#282828",
        promptCursorBackground: "#ebdbb2",
        promptCursorForeground: "#282828",
    },
});

export default gruvboxDarkTheme;
