import { createTheme } from "./helpers.js";

const noctisObscuroTheme = createTheme({
    id: "noctis-obscuro",
    label: "Noctis Obscuro",
    description: "Deep obsidian palette with cool blue accents and restrained contrast for long sessions.",
    page: {
        background: "#0b1117",
        foreground: "#c7d1da",
        overlayBackground: "#0b1117",
        overlayForeground: "#c7d1da",
        hintColor: "#7cc6ff",
        modalBackdrop: "rgba(5, 9, 13, 0.74)",
        modalBackground: "#121a23",
        modalBorder: "#28455b",
        modalForeground: "#d7e2eb",
        modalMuted: "#8f9dab",
        modalSelectedBackground: "#173041",
        modalSelectedBorder: "#7cc6ff",
        modalSelectedForeground: "#eef6ff",
    },
    terminal: {
        background: "#060b10",
        foreground: "#c7d1da",
        cursor: "#9fd4ff",
        cursorAccent: "#060b10",
        selectionBackground: "rgba(72, 125, 170, 0.30)",
        black: "#2a3138",
        red: "#ef6b73",
        green: "#7ddc8f",
        yellow: "#d9b36c",
        blue: "#68aee8",
        magenta: "#b28cff",
        cyan: "#58c9d4",
        white: "#c7d1da",
        brightBlack: "#6e7a86",
        brightRed: "#f28a92",
        brightGreen: "#97e5a6",
        brightYellow: "#e4c28b",
        brightBlue: "#86c1f1",
        brightMagenta: "#c6a7ff",
        brightCyan: "#7ad7df",
        brightWhite: "#e5edf5",
    },
    tui: {
        surface: "#060b10",
        activeHighlightBackground: "#123142",
        activeHighlightForeground: "#eef6ff",
        selectionBackground: "#4a7baa",
        selectionForeground: "#0b1117",
        promptCursorBackground: "#9fd4ff",
        promptCursorForeground: "#060b10",
    },
});

export default noctisObscuroTheme;