import { createTheme } from "./helpers.js";

const nordTheme = createTheme({
    id: "nord",
    label: "Nord",
    description: "Arctic blue-gray palette with frosty accents and clean contrast.",
    page: {
        background: "#2e3440",
        foreground: "#d8dee9",
        overlayBackground: "#2e3440",
        overlayForeground: "#d8dee9",
        hintColor: "#8f9ab5",
        modalBackdrop: "rgba(46, 52, 64, 0.74)",
        modalBackground: "#3b4252",
        modalBorder: "#4c566a",
        modalForeground: "#d8dee9",
        modalMuted: "#8f9ab5",
        modalSelectedBackground: "#434c5e",
        modalSelectedBorder: "#88c0d0",
        modalSelectedForeground: "#eceff4",
    },
    terminal: {
        background: "#2e3440",
        foreground: "#d8dee9",
        cursor: "#d8dee9",
        cursorAccent: "#2e3440",
        selectionBackground: "rgba(136, 192, 208, 0.22)",
        black: "#3b4252",
        red: "#bf616a",
        green: "#a3be8c",
        yellow: "#ebcb8b",
        blue: "#81a1c1",
        magenta: "#b48ead",
        cyan: "#88c0d0",
        white: "#e5e9f0",
        brightBlack: "#4c566a",
        brightRed: "#bf616a",
        brightGreen: "#a3be8c",
        brightYellow: "#ebcb8b",
        brightBlue: "#81a1c1",
        brightMagenta: "#b48ead",
        brightCyan: "#8fbcbb",
        brightWhite: "#eceff4",
    },
    tui: {
        surface: "#2e3440",
        activeHighlightBackground: "#434c5e",
        activeHighlightForeground: "#eceff4",
        selectionBackground: "#88c0d0",
        selectionForeground: "#2e3440",
        promptCursorBackground: "#d8dee9",
        promptCursorForeground: "#2e3440",
    },
});

export default nordTheme;
