import { createTheme } from "./helpers.js";

const solarizedLightTheme = createTheme({
    id: "solarized-light",
    label: "Solarized Light",
    description: "Ethan Schoonover's precision-engineered light palette with warm accents.",
    page: {
        background: "#fdf6e3",
        foreground: "#657b83",
        overlayBackground: "#fdf6e3",
        overlayForeground: "#657b83",
        hintColor: "#93a1a1",
        modalBackdrop: "rgba(253, 246, 227, 0.48)",
        modalBackground: "#eee8d5",
        modalBorder: "#93a1a1",
        modalForeground: "#657b83",
        modalMuted: "#93a1a1",
        modalSelectedBackground: "#eee8d5",
        modalSelectedBorder: "#268bd2",
        modalSelectedForeground: "#073642",
    },
    terminal: {
        background: "#fdf6e3",
        foreground: "#657b83",
        cursor: "#657b83",
        cursorAccent: "#fdf6e3",
        selectionBackground: "rgba(38, 139, 210, 0.18)",
        black: "#073642",
        red: "#dc322f",
        green: "#859900",
        yellow: "#b58900",
        blue: "#268bd2",
        magenta: "#d33682",
        cyan: "#2aa198",
        white: "#eee8d5",
        brightBlack: "#586e75",
        brightRed: "#cb4b16",
        brightGreen: "#93a1a1",
        brightYellow: "#839496",
        brightBlue: "#657b83",
        brightMagenta: "#6c71c4",
        brightCyan: "#586e75",
        brightWhite: "#fdf6e3",
    },
    tui: {
        surface: "#fdf6e3",
        activeHighlightBackground: "#eee8d5",
        activeHighlightForeground: "#073642",
        selectionBackground: "#268bd2",
        selectionForeground: "#fdf6e3",
        promptCursorBackground: "#657b83",
        promptCursorForeground: "#fdf6e3",
    },
});

export default solarizedLightTheme;
