import { createTheme } from "./helpers.js";

const tokyoNightTheme = createTheme({
    id: "tokyo-night",
    label: "Tokyo Night",
    description: "Deep blue-gray canvas with vivid neon accents inspired by Tokyo city lights.",
    page: {
        background: "#1a1b26",
        foreground: "#a9b1d6",
        overlayBackground: "#1a1b26",
        overlayForeground: "#a9b1d6",
        hintColor: "#737aa2",
        modalBackdrop: "rgba(26, 27, 38, 0.74)",
        modalBackground: "#24283b",
        modalBorder: "#414868",
        modalForeground: "#a9b1d6",
        modalMuted: "#737aa2",
        modalSelectedBackground: "#33467c",
        modalSelectedBorder: "#7aa2f7",
        modalSelectedForeground: "#c0caf5",
    },
    terminal: {
        background: "#1a1b26",
        foreground: "#a9b1d6",
        cursor: "#c0caf5",
        cursorAccent: "#1a1b26",
        selectionBackground: "rgba(122, 162, 247, 0.22)",
        black: "#414868",
        red: "#f7768e",
        green: "#9ece6a",
        yellow: "#e0af68",
        blue: "#7aa2f7",
        magenta: "#bb9af7",
        cyan: "#7dcfff",
        white: "#a9b1d6",
        brightBlack: "#565f89",
        brightRed: "#f7768e",
        brightGreen: "#9ece6a",
        brightYellow: "#e0af68",
        brightBlue: "#7aa2f7",
        brightMagenta: "#bb9af7",
        brightCyan: "#7dcfff",
        brightWhite: "#c0caf5",
    },
    tui: {
        surface: "#1a1b26",
        activeHighlightBackground: "#33467c",
        activeHighlightForeground: "#c0caf5",
        selectionBackground: "#7aa2f7",
        selectionForeground: "#1a1b26",
        promptCursorBackground: "#c0caf5",
        promptCursorForeground: "#1a1b26",
    },
});

export default tokyoNightTheme;
